### ISSUE TITLE
How do we stop pinging?

### ISSUE THREAD

**Issue by danhpham1510** [nopnop2002/esp-idf-ping#3]
Hello,

Thank you very much for making this library, this helps a lot. Can you also guide me on how to stop pinging, I'm very new to esp-idf.

All the best,
Danh.

**Comment by nopnop2002** [comment]
The firmware of a microcomputer keeps running as long as the power is on.

Turn off the power to stop.

It is possible to stop it by using button input etc., but you need to add the code for that.
